#!/bin/sh
OLD="/root/ics/431/oldkernel"
NEW="/root/ics/431/kernel"

cp -fr $OLD/arch/arm/mach-msm/board-msm7x30.c $NEW/arch/arm/mach-msm/.
cp -fr $OLD/arch/arm/mach-msm/acpuclock-7x30.c $NEW/arch/arm/mach-msm/.
cp -fr $OLD/arch/arm/mach-msm/clock-7x30.c $NEW/arch/arm/mach-msm/.
cp -fr $OLD/arch/arm/mach-msm/board-semc_mogami.c $NEW/arch/arm/mach-msm/.
cp -fr $OLD/arch/arm/mach-msm/pm2.c $NEW/arch/arm/mach-msm/.
cp -fr $OLD/arch/arm/configs/xkernel_urushi_defconfig $NEW/arch/arm/configs/.
cp -fr $OLD/arch/arm/mach-msm/qdsp5/* $NEW/arch/arm/mach-msm/qdsp5/.
cp -fr $OLD/arch/arm/mach-msm/qdsp5v2/* $NEW/arch/arm/mach-msm/qdsp5v2/.
cp -fr $OLD/arch/arm/mach-msm/qdsp6/* $NEW/arch/arm/mach-msm/qdsp6/.
cp -fr $OLD/arch/arm/mach-msm/qdsp6v2/* $NEW/arch/arm/mach-msm/qdsp6v2/.
cp -fr $OLD/drivers/staging/zram $NEW/drivers/staging/.
cp -fr $OLD/drivers/staging/zcache $NEW/drivers/staging/.
cp -fr $OLD/drivers/staging/mimio $NEW/drivers/staging/.
cp -fr $OLD/drivers/staging/Makefile $NEW/drivers/staging/.
cp -fr $OLD/drivers/staging/Kconfig $NEW/drivers/staging/.
cp -fr $OLD/drivers/cpufreq/* $NEW/drivers/cpufreq/.
cp -fr $OLD/drivers/gpu/msm/* $NEW/drivers/gpu/msm/.
cp -fr $OLD/include/linux/wakelock.h $NEW/include/linux/.
cp -fr $OLD/kernel_make $NEW/.
cp -fr $OLD/scripts/mkcompile_h $NEW/scripts/.
cp -fr $OLD/scripts/mod/modpost.c $NEW/scripts/mod/.
